1099/sender override failed message logger
mailbadger/app pull request #1100
Opened 2021-02-28 22:49 UTC by gudgl

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-01 07:53 UTC, FilipNikolovski requested changes

2021-03-01 07:53 UTC, FilipNikolovski commented on consumers/sender/main.go
> +		Description:  "Failed to send email five times",
```suggestion
		Description:  "Exceeded max attempts for sending the e-mail.",
```

2021-03-01 07:53 UTC, FilipNikolovski commented on consumers/sender/main.go
> +
We should also add an error log here as well.

2021-03-02 12:32 UTC, FilipNikolovski commented on consumers/sender/main.go
> +		"send_log_id":   msg.ID.String(),
You don't need to invoke String() explicitly I think.

```suggestion
		"send_log_id":   msg.ID,
```

2021-03-14 17:11 UTC, Dzalevski commented
@gudgl pull from master and clear go deps with `go mod tidy`

2021-03-17 07:55 UTC, FilipNikolovski approved these changes

2021-03-17 07:55 UTC, merged