Migration & Entity for Scheduled Campaigns
mailbadger/app pull request #1173
Opened 2021-04-03 00:04 UTC by Dzalevski

# Pull Request Template

## Description

This is only migration and entity for Scheduled Campaigns

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-04-03 12:25 UTC, gudgl commented on storage/migrations/mysql/5_scheduled_campaigns.sql
> +    `created_at`    datetime(6),
`created_at` and `updated_at` should also be `NOT NULL`

2021-04-04 16:30 UTC, FilipNikolovski requested changes

2021-04-04 16:30 UTC, FilipNikolovski commented on entities/campaignschedules.go
> +type CampaignSchedules struct {
```suggestion
type CampaignSchedule struct {
```

2021-04-04 16:30 UTC, FilipNikolovski commented on entities/campaign.go
> +	Schedules    *CampaignSchedules `json:"campaign_schedules" gorm:"foreignKey:campaign_id"`
```suggestion
	Schedule    *CampaignSchedule `json:"campaign_schedules" gorm:"foreignKey:campaign_id"`
```

2021-04-04 16:30 UTC, FilipNikolovski commented on storage/migrations/sqlite3/1_init.sql
> +  "id"                         integer primary key ,
Don't remove the autoincrement key this is the correct syntax https://sqlite.org/autoinc.html

2021-04-04 16:30 UTC, FilipNikolovski commented on storage/migrations/mysql/4_campaign_logs.sql
> +);
Revert this.

2021-04-04 16:30 UTC, FilipNikolovski commented on storage/migrations/mysql/5_campaign_schedules.sql
> +    `campaign_id`   integer unsigned    NOT NULL,
I'm thinking that the `campaign_id` should be unique, since we must have only one record of a schedule.

2021-04-04 16:30 UTC, FilipNikolovski commented on entities/campaign.go
> +	ScheduledAt  NullTime           `json:"scheduled_at" gorm:"column:scheduled_at"`
We should remove this field, along with the column in db.

2021-04-04 16:30 UTC, FilipNikolovski commented on entities/campaign.go
> +	Schedules    *CampaignSchedules `json:"campaign_schedules" gorm:"foreignKey:campaign_id"`
Should we add a `ScheduleID` field as well?

2021-04-04 18:03 UTC, FilipNikolovski requested changes

2021-04-04 18:03 UTC, FilipNikolovski commented on storage/campaignschedules.go
> +func (db *store) CreateScheduledCampaign(c *entities.CampaignSchedules) error {
```suggestion
func (db *store) CreateCampaignSchedule(c *entities.CampaignSchedules) error {
```

2021-04-04 18:03 UTC, FilipNikolovski commented on storage/campaignschedules.go
> +func (db *store) DeleteScheduledCampaign(campaignID int64) error {
```suggestion
func (db *store) DeleteCampaignSchedule(campaignID int64) error {
```

2021-04-04 20:56 UTC, gudgl commented on storage/migrations/mysql/5_campaign_schedules.sql
> +    );
@Dzalevski you are missing `CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;` at the end of create table

2021-04-05 06:34 UTC, FilipNikolovski approved these changes

2021-04-05 06:34 UTC, merged